<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{

    // You can keep them here or create an observer

//    protected static function boot()
//    {
//        parent::boot(); // TODO: Change the autogenerated stub
//        static::created(function ($task) {
//            $task->project->recordActivity('created_task');
//        });
//        static::updated(function ($task) {
//            if (!$task->completed) return;
//            $task->project->recordActivity('completed_task');
//        });
//    }

    protected $fillable = ['body', 'completed'];

    protected $touches = ['project'];

    protected $casts = ['completed' => 'boolean'];

    public function project()
    {
        return $this->belongsTo(Project::class);
    }

    public function path()
    {
        return "/projects/{$this->project->id}/tasks/{$this->id}";
    }

    public function complete()
    {
        $this->update(['completed' => true]);
    }

    public function incomplete()
    {
        $this->update(['completed' => false]);
        $this->recordActivity('incompleted_task');
    }

    public function recordActivity($description)
    {
        $this->activity()->create([
            'project_id' => $this->project_id,
            'description' => $description
        ]);
    }

    public function activity()
    {
        return $this->morphMany('App\Activity', 'subject')->latest();
    }
}
